"""
Scan screenshots/ folder and update README.md Demo Preview section for GitHub.

Usage:
    python scripts/sync_readme_screenshots.py
    git add README.md screenshots/
    git commit -m "Add demo screenshots"
    git push
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCREENSHOTS = ROOT / "screenshots"
README = ROOT / "README.md"
IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif"}
START = "<!-- SCREENSHOTS:START -->"
END = "<!-- SCREENSHOTS:END -->"


def collect_images() -> list[Path]:
    if not SCREENSHOTS.exists():
        return []
    return sorted(
        p for p in SCREENSHOTS.iterdir()
        if p.is_file() and p.suffix.lower() in IMAGE_EXTS
    )


def build_section(images: list[Path]) -> str:
    if not images:
        return f"""{START}
## Demo Preview

> **No screenshots yet.** Add `.png` or `.jpg` files to the [`screenshots/`](screenshots/) folder, then run:
>
> ```bash
> python scripts/sync_readme_screenshots.py
> git add README.md screenshots/
> git commit -m "Add demo screenshots"
> git push
> ```

_See [screenshots/README.md](screenshots/README.md) for the full checklist._

{END}"""

    lines = [
        START,
        "## Demo Preview",
        "",
        "Live demo screenshots from the **EduChain Nexus** web dashboard and lab exam outputs.",
        "",
    ]

    # Hero: first dashboard-looking image or first image
    hero = next(
        (i for i in images if "dashboard" in i.stem.lower() or "overview" in i.stem.lower()),
        images[0],
    )
    rel = f"screenshots/{hero.name}"
    title = hero.stem.replace("-", " ").replace("_", " ").title()
    lines += [
        f"### {title}",
        f"![{title}]({rel})",
        "",
    ]

    # Grid table for pairs
    others = [i for i in images if i != hero]
    if others:
        lines.append("| Screenshot | Preview |")
        lines.append("|------------|---------|")
        for i in range(0, len(others), 2):
            a = others[i]
            rel_a = f"screenshots/{a.name}"
            title_a = a.stem.replace("-", " ").replace("_", " ").title()
            if i + 1 < len(others):
                b = others[i + 1]
                rel_b = f"screenshots/{b.name}"
                title_b = b.stem.replace("-", " ").replace("_", " ").title()
                lines.append(
                    f"| **{title_a}** | **{title_b}** |"
                )
                lines.append(
                    f"| ![{title_a}]({rel_a}) | ![{title_b}]({rel_b}) |"
                )
            else:
                lines.append(f"| **{title_a}** | |")
                lines.append(f"| ![{title_a}]({rel_a}) | |")
        lines.append("")

    lines.append(f"_Total: {len(images)} screenshot(s) — auto-generated by `scripts/sync_readme_screenshots.py`_")
    lines.append(END)
    return "\n".join(lines)


def main() -> None:
    images = collect_images()
    section = build_section(images)
    text = README.read_text(encoding="utf-8")

    if START in text and END in text:
        text = re.sub(
            re.escape(START) + r".*?" + re.escape(END),
            section,
            text,
            flags=re.DOTALL,
        )
    else:
        # Insert after repository link block
        marker = "**Repository:**"
        if marker in text:
            idx = text.find("---", text.find(marker))
            text = text[:idx] + section + "\n\n---\n\n" + text[idx + 5:]
        else:
            text = section + "\n\n" + text

    README.write_text(text, encoding="utf-8")
    print(f"Updated README.md with {len(images)} screenshot(s).")
    if images:
        for img in images:
            print(f"  + {img.name}")
    else:
        print("  (no images found — add PNG/JPG files to screenshots/ folder)")


if __name__ == "__main__":
    main()
